version: '3'

volumes:
  paranuara_postgres_data: {}
  paranuara_postgres_data_backups: {}
  paranuara_files: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: paranuara_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
      - paranuara_files:/files
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: paranuara_local_postgres
    volumes:
      - paranuara_postgres_data:/var/lib/postgresql/data
      - paranuara_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
    - "5432:5432"

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: paranuara_local_celeryworker
    depends_on:
      - redis
      - postgres
      
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: paranuara_local_celerybeat
    depends_on:
      - redis
      - postgres
      
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: paranuara_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
